compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

pnpEnableEsmLoader: true

<<<<<<< HEAD
yarnPath: .yarn/releases/yarn-4.8.1.cjs
=======
yarnPath: .yarn/releases/yarn-4.9.1.cjs
>>>>>>> 9d52f15 (test: ✅ [AB-0001] fixed search tests)
